### ISSUE TITLE
can not run script

### ISSUE THREAD

**Issue by LodeBisschops** [Bios-Marcel/wastedonlol#2]
Hi i just cloned the script but i get an error when trying to execute it. 
I have requested a new key via the developers page and checked it again but i get the following error.

`PS C:\Users\bissc\Downloads\wastedonlol-master\wastedonlol-master> go run main.go --server="euw1" --apikey="x" --summonername="x"
# command-line-arguments
.\main.go:30:23: undefined: NewLimiter
.\main.go:31:23: undefined: NewLimiter`

**Comment by Bios-Marcel** [comment]
Which go version do you have?

**Comment by Bios-Marcel** [comment]
Oh, sorry, you have to do `go run .`
